### ISSUE TITLE
小白求助

### ISSUE THREAD

**Issue by hkreporters** [yuban10703/autopass-chaoxing-video#2]
按照readme里的操作后出现这个错误

Traceback (most recent call last):
  File "httpcore\_sync\http_proxy.py", line 227, in _tunnel_request
  File "httpcore\_sync\connection.py", line 136, in handle_request
  File "httpcore\_sync\connection.py", line 163, in _open_socket
  File "httpcore\_backends\sync.py", line 144, in open_tcp_stream
  File "contextlib.py", line 135, in __exit__
  File "httpcore\_exceptions.py", line 12, in map_exceptions
httpcore.ConnectTimeout: _ssl.c:1105: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "httpx\_transports\default.py", line 61, in map_httpcore_exceptions
  File "httpx\_transports\default.py", line 180, in handle_request
  File "httpcore\_sync\http_proxy.py", line 127, in handle_request
  File "httpcore\_sync\http_proxy.py", line 256, in _tunnel_request
httpcore.ProxyError: _ssl.c:1105: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 147, in <module>
  File "main.py", line 69, in main
  File "models\APIs.py", line 36, in login
  File "httpx\_client.py", line 1109, in post
  File "httpx\_client.py", line 787, in request
  File "httpx\_client.py", line 878, in send
  File "httpx\_client.py", line 908, in _send_handling_auth
  File "httpx\_client.py", line 947, in _send_handling_redirects
  File "httpx\_client.py", line 983, in _send_single_request
  File "httpx\_transports\default.py", line 180, in handle_request
  File "contextlib.py", line 135, in __exit__
  File "httpx\_transports\default.py", line 78, in map_httpcore_exceptions
httpx.ProxyError: _ssl.c:1105: The handshake operation timed out
[5372] Failed to execute script 'main' due to unhandled exception!

**Comment by yuban10703** [comment]
你开了代理吧

**Comment by hkreporters** [comment]
已解决，谢谢大大
