### ISSUE TITLE
小白再次求助

### ISSUE THREAD

**Issue by hkreporters** [yuban10703/autopass-chaoxing-video#3]
如下
Traceback (most recent call last):
  File "httpcore\_sync\http_proxy.py", line 227, in _tunnel_request
  File "httpcore\_sync\connection.py", line 136, in handle_request
  File "httpcore\_sync\connection.py", line 163, in _open_socket
  File "httpcore\_backends\sync.py", line 144, in open_tcp_stream
  File "contextlib.py", line 135, in __exit__
  File "httpcore\_exceptions.py", line 12, in map_exceptions
httpcore.ConnectError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "httpx\_transports\default.py", line 61, in map_httpcore_exceptions
  File "httpx\_transports\default.py", line 180, in handle_request
  File "httpcore\_sync\http_proxy.py", line 127, in handle_request
  File "httpcore\_sync\http_proxy.py", line 256, in _tunnel_request
httpcore.ProxyError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 147, in <module>
  File "main.py", line 69, in main
  File "models\APIs.py", line 36, in login
  File "httpx\_client.py", line 1109, in post
  File "httpx\_client.py", line 787, in request
  File "httpx\_client.py", line 878, in send
  File "httpx\_client.py", line 908, in _send_handling_auth
  File "httpx\_client.py", line 947, in _send_handling_redirects
  File "httpx\_client.py", line 983, in _send_single_request
  File "httpx\_transports\default.py", line 180, in handle_request
  File "contextlib.py", line 135, in __exit__
  File "httpx\_transports\default.py", line 78, in map_httpcore_exceptions
httpx.ProxyError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
[17572] Failed to execute script 'main' due to unhandled exception!
刚刚登了下发现以上问题。。
大佬（们）早点睡哈，晚安

**Comment by yuban10703** [comment]
貌似还是代理的问题
